// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS5o8UIqUkAkkdM7l4_JUfqeFNZjBQCr0',
    appId: '1:641747663956:web:d770fc1b753bc0ac0081c1',
    messagingSenderId: '641747663956',
    projectId: 'chat-app-91bb3',
    authDomain: 'chat-app-91bb3.firebaseapp.com',
    storageBucket: 'chat-app-91bb3.appspot.com',
    measurementId: 'G-CRKRDE92SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKONRlx7lFXVBGJMOImO-Ek0B1V_n2ygE',
    appId: '1:641747663956:android:8b10f1ae847035bf0081c1',
    messagingSenderId: '641747663956',
    projectId: 'chat-app-91bb3',
    storageBucket: 'chat-app-91bb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCojnui2seRpU0Le8ERbGx6c9jtOy5CYNM',
    appId: '1:641747663956:ios:498145d1828949a60081c1',
    messagingSenderId: '641747663956',
    projectId: 'chat-app-91bb3',
    storageBucket: 'chat-app-91bb3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCojnui2seRpU0Le8ERbGx6c9jtOy5CYNM',
    appId: '1:641747663956:ios:498145d1828949a60081c1',
    messagingSenderId: '641747663956',
    projectId: 'chat-app-91bb3',
    storageBucket: 'chat-app-91bb3.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS5o8UIqUkAkkdM7l4_JUfqeFNZjBQCr0',
    appId: '1:641747663956:web:dfa4bd7434cfda930081c1',
    messagingSenderId: '641747663956',
    projectId: 'chat-app-91bb3',
    authDomain: 'chat-app-91bb3.firebaseapp.com',
    storageBucket: 'chat-app-91bb3.appspot.com',
    measurementId: 'G-T2N42VN2ZL',
  );
}
